{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-data
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.storage.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- end }}
