apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
